mineral_catalog_2/mineral_catalog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
	path('minerals/', include('minerals.urls', namespace='minerals')),
    path('admin/', admin.site.urls),
    path('', views.index, name='Home'),
]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

mineral_catalog_2/minerals/urls.py
from django.urls import path

from . import views


app_name = 'minerals'
urlpatterns = [
    path('', views.mineral_list, name='list'),
    path('details/<pk>/', views.mineral_details, name='details'),
    path('search/<letter>/', views.mineral_by_letter, name='by_letter'),
    path('search/', views.search_term, name='search'),
    path('<group>/', views.group_search, name='group')
]

mineral_catalog_2/minerals/models.py
from django.db import models

# Create your models here.

class Mineral(models.Model):
    name = models.CharField(max_length=255)
    image_filename = models.CharField(max_length=255)
    image_caption = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    strunz_classification = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    crystal_system = models.CharField(max_length=255)
    unit_cell = models.CharField(max_length=255)
    crystal_symmetry = models.CharField(max_length=255)
    cleavage = models.CharField(max_length=255)
    mohs_scale_hardness = models.CharField(max_length=255)
    luster = models.CharField(max_length=255)
    streak = models.CharField(max_length=255)
    diaphaneity = models.CharField(max_length=255)
    optical_properties = models.CharField(max_length=255)
    refractive_index = models.CharField(max_length=255)
    crystal_habit = models.CharField(max_length=255)
    specific_gravity = models.CharField(max_length=255)
    group = models.CharField(max_length=255)

    def __str__(self):
        return self.name

mineral_catalog_2/mineral_catalog/views.py
from django.shortcuts import render

from minerals.models import Mineral


def index(request):
    minerals = Mineral.objects.filter(name__istartswith="A")
    return render(request, 'home.html', {'minerals': minerals})

mineral_catalog_2/minerals/views.py
from django.shortcuts import render, get_object_or_404

from .models import Mineral


def mineral_list(request):
    minerals = Mineral.objects.all()
    return render(request, 'minerals/mineral_list.html', {'minerals': minerals})


def mineral_details(request, pk):
    mineral = get_object_or_404(Mineral, pk=pk)
    fields = [field.name for field in Mineral._meta.get_fields()]
    fields = [entry for entry in fields if entry not in ('id', 'name', 'image_filename', 'image_caption')]
    return render(request, 'minerals/mineral_details.html', {'mineral': mineral, 'fields': fields,})


def mineral_by_letter(request, letter):
    minerals = Mineral.objects.filter(name__istartswith=letter)
    return render(request, 'minerals/mineral_list.html', {'minerals': minerals, 'letter': letter})


def search_term(request):
    term = request.GET.get('q')
    minerals = Mineral.objects.filter(name__icontains=term)
    return render(request, 'minerals/mineral_list.html', {'minerals': minerals})


def group_search(request, group):
    minerals = Mineral.objects.filter(group__icontains=group)
    return render(request, 'minerals/mineral_list.html', {'minerals': minerals, 'selected_group': group})

mineral_catalog_2/minerals/templates/minerals/group_list.html
{% for group in groups %}
  <div class="group">
      <li><a {% if group ==  selected_group %} style="font-weight: 700; font-size: 18px;"{% endif %} href="{% url 'minerals:group' group=group %}">{{ group }}</a></li>
  </div>
{% endfor %}

mineral_catalog_2/minerals/templates/minerals/mineral_details.html
{% extends 'layout.html' %}
{% load mineral_extras %}
{% load static from staticfiles %}
{% load static %}

{% block content %}
    <div class="grid-80 mineral__container">
      <h1 class="mineral__name">{{ mineral.name }}</h1>
      <div class="mineral__image-bg">
        <img class="mineral__image" src="{% get_static_prefix %}images/{{ mineral.name }}.jpg">
        <p class="mineral__caption">{{ mineral.image_caption }}</p>
      </div>
      <div class="mineral__table-container">
        <table class="mineral__table">
          {% for field in fields %}
            {% if mineral|getattribute:field %}
              <tr>
                <td class="mineral__category">{{ mineral|fieldname:field|title }}</td>
                <td>{{ mineral|getattribute:field|safe }}</td>
              </tr>
            {% endif %}
          {% endfor %}
        </table>
      </div>
    </div>
  {% endblock %}

mineral_catalog_2/minerals/templates/minerals/mineral_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="grid-80
    ">
      <ul class="minerals__container">
        {% for mineral in minerals %}
        <li class="minerals__item">
          <a class="minerals__anchor" href="{% url 'minerals:details' pk=mineral.pk %}">{{ mineral.name }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

mineral_catalog_2/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    <div class="grid-80">
      <ul class="minerals__container">
        {% for mineral in minerals %}
        <li class="minerals__item">
          <a class="minerals__anchor" href="{% url 'minerals:details' pk=mineral.pk %}">{{ mineral.name }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

mineral_catalog_2/templates/layout.html
<!DOCTYPE html>

{% load mineral_extras %}
{% load static from staticfiles %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Macky's Minerals: A magnificant catalog of minerals</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
  <div class="bounds">
    <div class="grid-100">
      <a href="{% url 'minerals:list' %}">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Macky's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
    </div>
    <section>
      <form action="{% url 'minerals:search' %}" method="GET">
        <div class='menu'>
          <input type='search' name='q'><button type='button' class='secondary small button'>Search
        </div>
      </form>
    </section>
    <div class="grid-100">
      <h6 class="text-centered"><span><a href="{% url 'minerals:list' %}">All</a></span>
      {% for i in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' %}
        <span {% if i == letter %} style="font-weight: 700; font-size: 18px;"{% endif %}>
          <a href="{% url 'minerals:by_letter' letter=i %}">{{ i }}</a>
        </span>
      {% endfor %}</h6>
    </div>
  <section class='grid-100'>
    <div class='grid-20'>
      {% group_list selected_group %}
    </div>
      {% block content %}
      {% endblock %}
  </section>
  <div class="minerals__random">
    {% random_pk as pk %}
    <a class="minerals__anchor" href="{% url 'minerals:details' pk=pk %}">Show random mineral</a>
  </div>
</body>
</html>